name: Validate PR

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: lint
        run: yarn lint

  test-client:
    name: Test Client
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: test
        run: yarn test:ci

  test-serverless:
    name: Test Serverless
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          check-latest: true
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: create env file

        run: |
          touch .env
          echo HASURA_API_URL=${{ secrets.HASURA_API_URL }} >> .env
          echo HASURA_GRAPHQL_ADMIN_SECRET=${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }} >> .env

      - name: test
        run: yarn test:serverless:ci
